##############
### COLORS ###
##############
foreground              #C1C497
background              #111C18
selection_foreground    #111C18
selection_background    #C1C497
cursor                  #D7C995
cursor_text_color       #000000
active_tab_foreground   #111C18
active_tab_background   #C1C497
inactive_tab_foreground #C1C497
inactive_tab_background #111C18
# black
color0  #23372B
color8  #53685B
# red
color1  #FF5345
color9  #DB9F9C
# green
color2  #549E6A
color10 #63b07a
# yellow
color3  #459451
color11 #E5C736
# blue
color4  #509475
color12 #ACD4CF
# magenta
color5  #D2689C
color13 #75BBB3
# cyan
color6  #2DD5B7
color14 #8CD3CB
# white
color7  #F6F5DD
color15 #9EEBB3

############
### FONT ###
############
font_family             JetBrainsMono Nerd Font
bold_font               auto
italic_font             auto
bold_italic_font        auto
font_size               11.0
modify_font cell_height 100%

##############
### WINDOW ###
##############
window_padding_width    4
hide_window_decorations yes
confirm_os_window_close 0
remember_window_size    no
background_opacity      0.80
background_blur         64

###################
### KEYBINDINGS ###
###################
# map ctrl+insert copy_to_clipboard
# map ctrl+insert paste_from_clipboard
allow_remote_control yes
shell	             zsh
shell_integration    disabled

##################
### AESTHETICS ###
##################
cursor_shape                  block
cursor_blink_interval         0
shell_integration             no-cursor
enable_audio_bell             no
tab_bar_edge                  bottom
tab_bar_style                 powerline
tab_powerline_style           slanted
tab_title_template            {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
scrollbar_handle_opacity      0
scrollbar_track_opacity       0
scrollbar_track_hover_opacity 0

