###########################
### APP-SPECIFIC TWEAKS ###
###########################
source = ~/.config/hypr/apps/browser.conf
source = ~/.config/hypr/apps/hyprshot.conf
source = ~/.config/hypr/apps/jetbrains.conf
source = ~/.config/hypr/apps/system.conf
source = ~/.config/hypr/apps/terminals.conf