##########################################
###         AUTOSTART PROCESEES        ###
### exec-once = uwsm-app -- my-service ###
##########################################

exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- waybar
exec-once = uwsm-app -- swww-daemon
exec-once = uwsm-app -- swww img ~/.config/meta/current/background
